// GENERATED by scripts/generate-env.mjs — do not edit by hand.
export const ENV = {
  supabaseUrl: 'https://domneconesznimnzxdsx.supabase.co',
  supabaseAnonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbW5lY29uZXN6bmltbnp4ZHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ5MDI4ODksImV4cCI6MjEwMDQ3ODg4OX0.gdRg0Q4kXuI-N-Ph4Nou5qRq1nuxxCogcckzG6witho',
} as const;
