// GENERATED by `supabase gen types typescript --linked` — do not edit by hand.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      activities: {
        Row: {
          cost_level: number | null
          created_at: string
          created_by: string | null
          description: string | null
          duration_min: number | null
          embedding: string | null
          external_id: string | null
          external_source: string | null
          id: string
          image_url: string | null
          is_public: boolean
          location: Json | null
          metadata: Json
          title: string
          type: Database["public"]["Enums"]["activity_type"]
          updated_at: string
        }
        Insert: {
          cost_level?: number | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          duration_min?: number | null
          embedding?: string | null
          external_id?: string | null
          external_source?: string | null
          id?: string
          image_url?: string | null
          is_public?: boolean
          location?: Json | null
          metadata?: Json
          title: string
          type: Database["public"]["Enums"]["activity_type"]
          updated_at?: string
        }
        Update: {
          cost_level?: number | null
          created_at?: string
          created_by?: string | null
          description?: string | null
          duration_min?: number | null
          embedding?: string | null
          external_id?: string | null
          external_source?: string | null
          id?: string
          image_url?: string | null
          is_public?: boolean
          location?: Json | null
          metadata?: Json
          title?: string
          type?: Database["public"]["Enums"]["activity_type"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "activities_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      activity_availability: {
        Row: {
          activity_id: string
          available_since: string | null
          deeplink_url: string | null
          id: string
          last_checked_at: string
          leaving_at: string | null
          offer: Database["public"]["Enums"]["offer_type"]
          price_cents: number | null
          region: string
          service_id: string
        }
        Insert: {
          activity_id: string
          available_since?: string | null
          deeplink_url?: string | null
          id?: string
          last_checked_at?: string
          leaving_at?: string | null
          offer: Database["public"]["Enums"]["offer_type"]
          price_cents?: number | null
          region?: string
          service_id: string
        }
        Update: {
          activity_id?: string
          available_since?: string | null
          deeplink_url?: string | null
          id?: string
          last_checked_at?: string
          leaving_at?: string | null
          offer?: Database["public"]["Enums"]["offer_type"]
          price_cents?: number | null
          region?: string
          service_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_availability_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_availability_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "streaming_services"
            referencedColumns: ["id"]
          },
        ]
      }
      activity_tags: {
        Row: {
          activity_id: string
          tag_id: string
        }
        Insert: {
          activity_id: string
          tag_id: string
        }
        Update: {
          activity_id?: string
          tag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_tags_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
        ]
      }
      ai_invocations: {
        Row: {
          cost_usd: number | null
          created_at: string
          id: string
          input_tokens: number | null
          model: string
          output_tokens: number | null
          party_id: string | null
          purpose: string
        }
        Insert: {
          cost_usd?: number | null
          created_at?: string
          id?: string
          input_tokens?: number | null
          model: string
          output_tokens?: number | null
          party_id?: string | null
          purpose: string
        }
        Update: {
          cost_usd?: number | null
          created_at?: string
          id?: string
          input_tokens?: number | null
          model?: string
          output_tokens?: number | null
          party_id?: string | null
          purpose?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_invocations_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "parties"
            referencedColumns: ["id"]
          },
        ]
      }
      connections: {
        Row: {
          created_at: string
          friend_id: string
          status: string
          user_id: string
        }
        Insert: {
          created_at?: string
          friend_id: string
          status?: string
          user_id: string
        }
        Update: {
          created_at?: string
          friend_id?: string
          status?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "connections_friend_id_fkey"
            columns: ["friend_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "connections_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      episode_progress: {
        Row: {
          episode_id: string
          user_id: string
          watched_at: string
        }
        Insert: {
          episode_id: string
          user_id: string
          watched_at?: string
        }
        Update: {
          episode_id?: string
          user_id?: string
          watched_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "episode_progress_episode_id_fkey"
            columns: ["episode_id"]
            isOneToOne: false
            referencedRelation: "media_episodes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "episode_progress_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      group_members: {
        Row: {
          group_id: string
          user_id: string
        }
        Insert: {
          group_id: string
          user_id: string
        }
        Update: {
          group_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "group_members_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "group_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      groups: {
        Row: {
          created_at: string
          group_embedding: string | null
          id: string
          name: string
          owner_id: string
        }
        Insert: {
          created_at?: string
          group_embedding?: string | null
          id?: string
          name: string
          owner_id: string
        }
        Update: {
          created_at?: string
          group_embedding?: string | null
          id?: string
          name?: string
          owner_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "groups_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      media_episodes: {
        Row: {
          air_date: string | null
          episode_number: number
          id: string
          runtime_min: number | null
          season_id: string
          title: string | null
        }
        Insert: {
          air_date?: string | null
          episode_number: number
          id?: string
          runtime_min?: number | null
          season_id: string
          title?: string | null
        }
        Update: {
          air_date?: string | null
          episode_number?: number
          id?: string
          runtime_min?: number | null
          season_id?: string
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "media_episodes_season_id_fkey"
            columns: ["season_id"]
            isOneToOne: false
            referencedRelation: "media_seasons"
            referencedColumns: ["id"]
          },
        ]
      }
      media_seasons: {
        Row: {
          activity_id: string
          air_date: string | null
          episode_count: number | null
          id: string
          season_number: number
        }
        Insert: {
          activity_id: string
          air_date?: string | null
          episode_count?: number | null
          id?: string
          season_number: number
        }
        Update: {
          activity_id?: string
          air_date?: string | null
          episode_count?: number | null
          id?: string
          season_number?: number
        }
        Relationships: [
          {
            foreignKeyName: "media_seasons_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
        ]
      }
      parties: {
        Row: {
          activity_type: Database["public"]["Enums"]["activity_type"] | null
          constraints: Json
          created_at: string
          decided_activity_id: string | null
          decided_at: string | null
          decision_config: Json
          group_id: string | null
          host_id: string
          id: string
          join_code: string | null
          status: Database["public"]["Enums"]["party_status"]
        }
        Insert: {
          activity_type?: Database["public"]["Enums"]["activity_type"] | null
          constraints?: Json
          created_at?: string
          decided_activity_id?: string | null
          decided_at?: string | null
          decision_config?: Json
          group_id?: string | null
          host_id: string
          id?: string
          join_code?: string | null
          status?: Database["public"]["Enums"]["party_status"]
        }
        Update: {
          activity_type?: Database["public"]["Enums"]["activity_type"] | null
          constraints?: Json
          created_at?: string
          decided_activity_id?: string | null
          decided_at?: string | null
          decision_config?: Json
          group_id?: string | null
          host_id?: string
          id?: string
          join_code?: string | null
          status?: Database["public"]["Enums"]["party_status"]
        }
        Relationships: [
          {
            foreignKeyName: "parties_decided_activity_id_fkey"
            columns: ["decided_activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parties_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parties_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      party_candidates: {
        Row: {
          activity_id: string
          ai_blurb: string | null
          created_at: string
          final_score: number | null
          id: string
          party_id: string
          presented_order: number | null
          score_breakdown: Json
        }
        Insert: {
          activity_id: string
          ai_blurb?: string | null
          created_at?: string
          final_score?: number | null
          id?: string
          party_id: string
          presented_order?: number | null
          score_breakdown?: Json
        }
        Update: {
          activity_id?: string
          ai_blurb?: string | null
          created_at?: string
          final_score?: number | null
          id?: string
          party_id?: string
          presented_order?: number | null
          score_breakdown?: Json
        }
        Relationships: [
          {
            foreignKeyName: "party_candidates_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_candidates_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "parties"
            referencedColumns: ["id"]
          },
        ]
      }
      party_members: {
        Row: {
          guest_name: string | null
          guest_profile: Json | null
          id: string
          joined_at: string
          party_id: string
          role: string
          user_id: string | null
        }
        Insert: {
          guest_name?: string | null
          guest_profile?: Json | null
          id?: string
          joined_at?: string
          party_id: string
          role?: string
          user_id?: string | null
        }
        Update: {
          guest_name?: string | null
          guest_profile?: Json | null
          id?: string
          joined_at?: string
          party_id?: string
          role?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "party_members_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: false
            referencedRelation: "parties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      party_mood_checkins: {
        Row: {
          created_at: string
          energy: number | null
          free_text: string | null
          id: string
          member_id: string
          mood_tags: string[]
        }
        Insert: {
          created_at?: string
          energy?: number | null
          free_text?: string | null
          id?: string
          member_id: string
          mood_tags?: string[]
        }
        Update: {
          created_at?: string
          energy?: number | null
          free_text?: string | null
          id?: string
          member_id?: string
          mood_tags?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "party_mood_checkins_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "party_members"
            referencedColumns: ["id"]
          },
        ]
      }
      party_outcomes: {
        Row: {
          did_it: boolean | null
          group_rating: number | null
          notes: string | null
          party_id: string
          recorded_at: string
        }
        Insert: {
          did_it?: boolean | null
          group_rating?: number | null
          notes?: string | null
          party_id: string
          recorded_at?: string
        }
        Update: {
          did_it?: boolean | null
          group_rating?: number | null
          notes?: string | null
          party_id?: string
          recorded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_outcomes_party_id_fkey"
            columns: ["party_id"]
            isOneToOne: true
            referencedRelation: "parties"
            referencedColumns: ["id"]
          },
        ]
      }
      party_swipes: {
        Row: {
          candidate_id: string
          direction: Database["public"]["Enums"]["swipe_direction"]
          id: string
          member_id: string
          swiped_at: string
        }
        Insert: {
          candidate_id: string
          direction: Database["public"]["Enums"]["swipe_direction"]
          id?: string
          member_id: string
          swiped_at?: string
        }
        Update: {
          candidate_id?: string
          direction?: Database["public"]["Enums"]["swipe_direction"]
          id?: string
          member_id?: string
          swiped_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_swipes_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "party_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_swipes_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "party_members"
            referencedColumns: ["id"]
          },
        ]
      }
      party_vetoes: {
        Row: {
          candidate_id: string
          member_id: string
        }
        Insert: {
          candidate_id: string
          member_id: string
        }
        Update: {
          candidate_id?: string
          member_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_vetoes_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "party_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_vetoes_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "party_members"
            referencedColumns: ["id"]
          },
        ]
      }
      party_votes: {
        Row: {
          candidate_id: string
          id: string
          member_id: string
          points: number
          voted_at: string
        }
        Insert: {
          candidate_id: string
          id?: string
          member_id: string
          points?: number
          voted_at?: string
        }
        Update: {
          candidate_id?: string
          id?: string
          member_id?: string
          points?: number
          voted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "party_votes_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "party_candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "party_votes_member_id_fkey"
            columns: ["member_id"]
            isOneToOne: false
            referencedRelation: "party_members"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_subscriptions: {
        Row: {
          created_at: string
          profile_id: string
          subscriber_id: string
        }
        Insert: {
          created_at?: string
          profile_id: string
          subscriber_id: string
        }
        Update: {
          created_at?: string
          profile_id?: string
          subscriber_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_subscriptions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_subscriptions_subscriber_id_fkey"
            columns: ["subscriber_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          display_name: string
          friend_code: string | null
          home_location: Json | null
          home_region: string | null
          id: string
          settings: Json
          taste_embedding: string | null
          taste_embedding_updated_at: string | null
          visibility: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          display_name: string
          friend_code?: string | null
          home_location?: Json | null
          home_region?: string | null
          id: string
          settings?: Json
          taste_embedding?: string | null
          taste_embedding_updated_at?: string | null
          visibility?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          display_name?: string
          friend_code?: string | null
          home_location?: Json | null
          home_region?: string | null
          id?: string
          settings?: Json
          taste_embedding?: string | null
          taste_embedding_updated_at?: string | null
          visibility?: string
        }
        Relationships: []
      }
      radar_slot_items: {
        Row: {
          activity_id: string
          added_at: string
          added_by: string | null
          note: string | null
          position: number
          slot_id: string
        }
        Insert: {
          activity_id: string
          added_at?: string
          added_by?: string | null
          note?: string | null
          position?: number
          slot_id: string
        }
        Update: {
          activity_id?: string
          added_at?: string
          added_by?: string | null
          note?: string | null
          position?: number
          slot_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "radar_slot_items_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "radar_slot_items_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "radar_slot_items_slot_id_fkey"
            columns: ["slot_id"]
            isOneToOne: false
            referencedRelation: "radar_slots"
            referencedColumns: ["id"]
          },
        ]
      }
      radar_slots: {
        Row: {
          config: Json
          created_at: string
          description: string | null
          emoji: string | null
          group_id: string | null
          id: string
          name: string
          on_complete: string
          owner_id: string | null
          position: number
          visibility: string
        }
        Insert: {
          config?: Json
          created_at?: string
          description?: string | null
          emoji?: string | null
          group_id?: string | null
          id?: string
          name: string
          on_complete?: string
          owner_id?: string | null
          position?: number
          visibility?: string
        }
        Update: {
          config?: Json
          created_at?: string
          description?: string | null
          emoji?: string | null
          group_id?: string | null
          id?: string
          name?: string
          on_complete?: string
          owner_id?: string | null
          position?: number
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "radar_slots_group_id_fkey"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "radar_slots_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      rainchecks: {
        Row: {
          activity_id: string
          created_at: string
          id: string
          member_ids: string[]
          source_party_id: string | null
          status: string
        }
        Insert: {
          activity_id: string
          created_at?: string
          id?: string
          member_ids: string[]
          source_party_id?: string | null
          status?: string
        }
        Update: {
          activity_id?: string
          created_at?: string
          id?: string
          member_ids?: string[]
          source_party_id?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "rainchecks_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rainchecks_source_party_id_fkey"
            columns: ["source_party_id"]
            isOneToOne: false
            referencedRelation: "parties"
            referencedColumns: ["id"]
          },
        ]
      }
      slot_likes: {
        Row: {
          created_at: string
          slot_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          slot_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          slot_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "slot_likes_slot_id_fkey"
            columns: ["slot_id"]
            isOneToOne: false
            referencedRelation: "radar_slots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "slot_likes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      slot_subscriptions: {
        Row: {
          created_at: string
          last_seen_at: string
          slot_id: string
          subscriber_id: string
        }
        Insert: {
          created_at?: string
          last_seen_at?: string
          slot_id: string
          subscriber_id: string
        }
        Update: {
          created_at?: string
          last_seen_at?: string
          slot_id?: string
          subscriber_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "slot_subscriptions_slot_id_fkey"
            columns: ["slot_id"]
            isOneToOne: false
            referencedRelation: "radar_slots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "slot_subscriptions_subscriber_id_fkey"
            columns: ["subscriber_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      slot_tags: {
        Row: {
          slot_id: string
          tag_id: string
        }
        Insert: {
          slot_id: string
          tag_id: string
        }
        Update: {
          slot_id?: string
          tag_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "slot_tags_slot_id_fkey"
            columns: ["slot_id"]
            isOneToOne: false
            referencedRelation: "radar_slots"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "slot_tags_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
        ]
      }
      streaming_services: {
        Row: {
          id: string
          logo_url: string | null
          name: string
          slug: string
          tmdb_provider_id: number | null
          watchmode_id: number | null
        }
        Insert: {
          id?: string
          logo_url?: string | null
          name: string
          slug: string
          tmdb_provider_id?: number | null
          watchmode_id?: number | null
        }
        Update: {
          id?: string
          logo_url?: string | null
          name?: string
          slug?: string
          tmdb_provider_id?: number | null
          watchmode_id?: number | null
        }
        Relationships: []
      }
      tags: {
        Row: {
          id: string
          kind: Database["public"]["Enums"]["tag_kind"]
          label: string
          slug: string
        }
        Insert: {
          id?: string
          kind: Database["public"]["Enums"]["tag_kind"]
          label: string
          slug: string
        }
        Update: {
          id?: string
          kind?: Database["public"]["Enums"]["tag_kind"]
          label?: string
          slug?: string
        }
        Relationships: []
      }
      user_dealbreakers: {
        Row: {
          created_at: string
          id: string
          is_active: boolean
          kind: string
          user_id: string
          value: Json
        }
        Insert: {
          created_at?: string
          id?: string
          is_active?: boolean
          kind: string
          user_id: string
          value: Json
        }
        Update: {
          created_at?: string
          id?: string
          is_active?: boolean
          kind?: string
          user_id?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "user_dealbreakers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_engagements: {
        Row: {
          activity_id: string
          completed_at: string | null
          context: Json
          id: string
          is_rewatchable: boolean | null
          notes: string | null
          rating: number | null
          recommended_by: string | null
          recommended_by_user_id: string | null
          review: string | null
          source: string
          started_at: string | null
          status: Database["public"]["Enums"]["engagement_status"]
          updated_at: string
          user_id: string
          visibility: string
        }
        Insert: {
          activity_id: string
          completed_at?: string | null
          context?: Json
          id?: string
          is_rewatchable?: boolean | null
          notes?: string | null
          rating?: number | null
          recommended_by?: string | null
          recommended_by_user_id?: string | null
          review?: string | null
          source?: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["engagement_status"]
          updated_at?: string
          user_id: string
          visibility?: string
        }
        Update: {
          activity_id?: string
          completed_at?: string | null
          context?: Json
          id?: string
          is_rewatchable?: boolean | null
          notes?: string | null
          rating?: number | null
          recommended_by?: string | null
          recommended_by_user_id?: string | null
          review?: string | null
          source?: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["engagement_status"]
          updated_at?: string
          user_id?: string
          visibility?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_engagements_activity_id_fkey"
            columns: ["activity_id"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_engagements_recommended_by_user_id_fkey"
            columns: ["recommended_by_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_engagements_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_subscriptions: {
        Row: {
          is_active: boolean
          service_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          is_active?: boolean
          service_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          is_active?: boolean
          service_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_subscriptions_service_id_fkey"
            columns: ["service_id"]
            isOneToOne: false
            referencedRelation: "streaming_services"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_tag_affinities: {
        Row: {
          source: string
          tag_id: string
          updated_at: string
          user_id: string
          weight: number
        }
        Insert: {
          source?: string
          tag_id: string
          updated_at?: string
          user_id: string
          weight?: number
        }
        Update: {
          source?: string
          tag_id?: string
          updated_at?: string
          user_id?: string
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "user_tag_affinities_tag_id_fkey"
            columns: ["tag_id"]
            isOneToOne: false
            referencedRelation: "tags"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_tag_affinities_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_friend_by_code: { Args: { p_code: string }; Returns: string }
      is_friend: { Args: { p_user: string }; Returns: boolean }
      is_party_member: { Args: { p_party_id: string }; Returns: boolean }
      join_party: { Args: { p_code: string }; Returns: string }
      recommend_to_friend: {
        Args: { p_activity_id: string; p_friend_id: string }
        Returns: undefined
      }
      recompute_affinities: { Args: { p_user_id: string }; Returns: undefined }
      taste_match: { Args: { p_other: string }; Returns: number }
    }
    Enums: {
      activity_type:
        | "movie"
        | "tv_show"
        | "restaurant"
        | "live_performance"
        | "outing"
        | "custom"
        | "book"
      engagement_status:
        | "want_to"
        | "in_progress"
        | "completed"
        | "abandoned"
        | "not_interested"
      offer_type: "subscription" | "free" | "ads" | "rent" | "buy"
      party_status:
        | "gathering"
        | "swiping"
        | "voting"
        | "decided"
        | "completed"
        | "cancelled"
      swipe_direction: "left" | "right" | "super"
      tag_kind:
        | "genre"
        | "cuisine"
        | "performance_type"
        | "vibe"
        | "theme"
        | "content_warning"
        | "dietary"
        | "accessibility"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      activity_type: [
        "movie",
        "tv_show",
        "restaurant",
        "live_performance",
        "outing",
        "custom",
        "book",
      ],
      engagement_status: [
        "want_to",
        "in_progress",
        "completed",
        "abandoned",
        "not_interested",
      ],
      offer_type: ["subscription", "free", "ads", "rent", "buy"],
      party_status: [
        "gathering",
        "swiping",
        "voting",
        "decided",
        "completed",
        "cancelled",
      ],
      swipe_direction: ["left", "right", "super"],
      tag_kind: [
        "genre",
        "cuisine",
        "performance_type",
        "vibe",
        "theme",
        "content_warning",
        "dietary",
        "accessibility",
      ],
    },
  },
} as const
