// Generates src/environments/env.generated.ts from environment variables.
// Runs automatically via the `prebuild`/`prestart` npm hooks.
//
// Sources, in priority order:
//   1. Real environment variables (what Vercel uses at build time)
//   2. A local `.env` file at the repo root (gitignored; see .env.example)
//
// These values are PUBLIC (the Supabase anon key is designed to ship to the
// browser; RLS protects the data). Secrets (GEMINI_API_KEY, TMDB_API_KEY)
// live only in Supabase Edge Function secrets and must never appear here.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const env = { ...process.env };
if (existsSync('.env')) {
  for (const line of readFileSync('.env', 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (m && env[m[1]] === undefined) {
      env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
    }
  }
}

const supabaseUrl = env.NG_APP_SUPABASE_URL ?? '';
const supabaseAnonKey = env.NG_APP_SUPABASE_ANON_KEY ?? '';

mkdirSync('src/environments', { recursive: true });
writeFileSync(
  'src/environments/env.generated.ts',
  `// GENERATED by scripts/generate-env.mjs — do not edit by hand.
export const ENV = {
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
} as const;
`,
);

console.log(
  supabaseUrl
    ? '[generate-env] env.generated.ts written (Supabase config present)'
    : '[generate-env] env.generated.ts written EMPTY — set NG_APP_SUPABASE_URL / NG_APP_SUPABASE_ANON_KEY (see .env.example)',
);
