// GENERATED by scripts/build-release-notes.mjs — do not edit by hand.
// Source of truth: docs/release-notes/*.md · rebuild with `npm run notes:build`.
import type { ReleaseNote } from './release-notes';

/** Newest first. */
export const RELEASE_NOTES: readonly ReleaseNote[] = [
  {
    seq: 11,
    version: "0.11",
    date: "2026-07-31",
    title: "Quests, rebuilt — and adventures",
    summary: "Quests now run on the slots you and your friends already keep, with no AI and no rules to fill in. And a night out can become a whole itinerary.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Pick the slots, get the deck", text: "Start a quest by choosing what kind of night it is (watch, eat, do or read) and that's it. Everyone in the quest then picks up to three slots to throw in — their own, ones they've saved from other people, or anybody else's in the quest — and you swipe through everything in them." },
          { lead: "See what you're picking", text: "Every slot on offer shows a cover collage, how many things are in it, and whose it is. Tap one to look inside at the full list without leaving the quest." },
          { lead: "Watch the pot fill up", text: "Everyone's picks appear live as they're made, so you can see what the night is shaping up to be before it starts." },
          { lead: "Nobody has to pick", text: "Three each is the cap, zero is fine, as long as somebody puts something in." },
          { lead: "Adventures", text: "Turn a quest into an itinerary with \"Make it an adventure!\". Add as many more quests as you like, in any mix of watch, eat, do and read — a movie marathon, a date night, a whole weekend away." },
          { lead: "One code for the whole trip", text: "An adventure keeps the roster of the quest it grew from and inherits its code. Anyone joining with it lands in every quest at once; nobody re-joins for day two." },
          { lead: "A day-by-day plan", text: "Give a quest a date and time and it slots under its day heading. Anything without a time waits in a Maybe list you can reorder, and giving it a time moves it up into the schedule." },
          { lead: "Change the plan", text: "Add or drop quests, re-time them, or clear a time to push something back to Maybe. Quests you've already decided are kept as history rather than deleted." },
          { lead: "The recap", text: "Completing an adventure gives you a keepsake: everything the group decided, when, and who was there." },
          { lead: "Bail out", text: "Hosts can cancel a quest or an adventure mid-flight. You'll be asked if you're sure, and then called a Party Pooper for it." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "No more AI picks", text: "The Gemini rerank and the fetch-fresh-suggestions step are gone. Between the guesswork and the gaps in what we could look up, the decks weren't good enough. What's on your radar already is better." },
          { lead: "No more constraints", text: "Runtime caps, film-or-show, and only-things- everyone-can-stream are all gone. You pick slots; everything in them is in the running." },
          { lead: "Quests work in all four domains", text: "Not just films and shows. Dinner quests, day-out quests, and what-should-we-all-read quests now work the same way." },
          { lead: "Ties are settled by a coin flip", text: "If two things finish level on votes, the winner is drawn at random instead of being decided by a hidden score." },
          { lead: "No more mood check-in", text: "Energy sliders and vibe chips only existed to brief the AI. The lobby now shows who's put slots in instead." },
          { lead: "Swipe cards are cleaner", text: "The fit ring and the AI blurb are gone, replaced by how many cards you have left." },
          { lead: "Start over means re-pick", text: "Restarting a quest hands it back to slot picking rather than fetching a fresh shortlist. Your picks are kept so you can adjust rather than start from nothing." },
          { lead: "Your taste chips are honest now", text: "They used to say parties used them immediately, which stopped being true when the AI picks went. They shape your taste match with friends." },
        ],
      },
      {
        heading: "Removed",
        items: [
          { lead: "The suggestion engine", text: "The candidate-generation service and its scoring have been retired along with the external look-ups they depended on." },
        ],
      },
    ],
  },
  {
    seq: 10,
    version: "0.10",
    date: "2026-07-31",
    title: "Notifications and What's new",
    summary: "A notification bell on your profile and a dot on the Me tab, so you hear when friends act on what you sent them — and see what changed in each release.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Notifications", text: "A bell on the You page with a count of what's waiting, and a matching dot on the Me tab so you can see it from anywhere in the app. Tap anything in the list to jump straight to what it's about." },
          { lead: "What's new", text: "When a release lands, a single entry appears in your notifications. Open it once and you get every note you haven't read yet, not one tap per release." },
          { lead: "Release notes archive", text: "Every release Radar has ever shipped, from the You page, including everything built before this system existed." },
          { lead: "\"They started it\" and \"they finished it\"", text: "When a friend starts or finishes something you recommended to them, you hear about it, with their rating if they left one." },
          { lead: "\"Someone sent you something\"", text: "The friend on the receiving end of a recommendation now gets told, instead of quietly finding it in a slot later." },
          { lead: "Slot finished", text: "When someone who saved one of your slots finishes the last thing in it, you get to know." },
          { lead: "New friend", text: "You're told when someone adds you with your friend code." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "Your profile has a header", text: "Your initial, your name, and the bell now sit at the top of the You page." },
        ],
      },
    ],
  },
  {
    seq: 9,
    version: "0.9",
    date: "2026-07-26",
    title: "Social slots",
    summary: "Slots work like playlists now — share them, like them, save someone else's to your own radar, and browse what other people have built.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Slot visibility", text: "Every slot is public, friends-only, or private, set per slot. Existing slots stayed friends-only, exactly as they were." },
          { lead: "Profile visibility", text: "The same three settings for your whole profile, on the You page." },
          { lead: "Descriptions and tags on slots", text: "Say what a slot is for and tag it, so people can tell \"Halloween\" from \"Halloween\"." },
          { lead: "Thumbs-up", text: "Like a slot you enjoy. Like counts are public; who's subscribed to you stays yours alone." },
          { lead: "Save a slot to your radar", text: "Keep a live link to someone else's slot. It updates when they add to it, with a badge for what's new since you last looked, and shows how far through it you are." },
          { lead: "Fork a slot", text: "Take a copy you can edit, with credit to whoever built it." },
          { lead: "Follow a profile", text: "Keep up with someone's radar without being friends." },
          { lead: "Taste match", text: "A single percentage on someone's profile showing how much your tastes overlap. Nothing about your ratings is ever exposed to work it out." },
          { lead: "Explore → Slots", text: "Discover public and friends' slots per domain, with 2x2 cover collages, who made them, like counts, tags, and popular or newest sorting." },
          { lead: "Explore → People", text: "Find public profiles by name, with a Featured rail for curators." },
          { lead: "Quest from a slot", text: "Start a party that picks only from one chosen slot, yours or one you've saved. Everything else about the night works the same." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "Slot pages open for anyone allowed to see them", text: "As the owner you get visibility, editing, reordering and your stats. As a visitor you get like, save, fork, share, and your own progress through it." },
          { lead: "Saved slots on the Radar home", text: "A section for slots you've saved from other people, separate from your own." },
          { lead: "Friends tab includes people you follow", text: "Not just mutual friends." },
        ],
      },
    ],
  },
  {
    seq: 8,
    version: "0.8",
    date: "2026-07-25",
    title: "Do and Read",
    summary: "Two more domains — places to go and books to read — sharing all the same slots, search and recommendations.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Do domain", text: "Places to go: museums, galleries, zoos, amusement parks, mini golf. Searchable nearby with a wider radius than restaurants." },
          { lead: "Read domain", text: "Books, with author, page count, year, rating, and a link out to Google Books." },
          { lead: "Starter slots for both", text: "Want to go and Favourites for Do; Reading, Want to read and Favourites for Read." },
          { lead: "Statuses that fit", text: "Want to go / Been there for places; Want to read / Reading / Finished for books, each with its own would-do-again toggle." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "Four domains in the switcher", text: "Watch, Eat, Do and Read now sit in a scrollable row on both Radar and Explore, with filters tuned per domain." },
          { lead: "Recommendations know all four", text: "Sending a friend a book, a place, or a restaurant puts it in the matching slot on their radar." },
        ],
      },
    ],
  },
  {
    seq: 7,
    version: "0.7",
    date: "2026-07-25",
    title: "Explore, slot pages, and a new look",
    summary: "A proper discovery browser with real filters, dedicated pages for each slot, a rebuilt tab bar, and a new app icon.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Explore", text: "A browsing screen over everything Radar knows, with filters that actually work: for films and shows, what's on your services, hide what you've seen, runtime, decade, rating floor, and genres; for restaurants, open-now, distance, price, rating, and cuisine. Sort by popular, rating, newest, closest, or A-Z." },
          { lead: "Friend signals in Explore", text: "Coloured initials next to a title show which friends want it, are watching it, or loved it." },
          { lead: "One-tap add from Explore", text: "Put anything you spot straight onto your radar." },
          { lead: "Slot pages", text: "Every slot gets its own page: the full queue, the same search and filters as Explore, sorting, and reordering." },
          { lead: "My Radar on title pages", text: "Tap to drop a title into any of your custom slots without leaving the page." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "New bottom nav", text: "Five even tabs — Radar, Explore, Quests, Friends, Me — with new icons and a gold active state. Parties are now \"Quests\" and live in a normal tab instead of a big centre button." },
          { lead: "Full-bleed to the top", text: "The app runs edge to edge on the phone, with content and toasts clearing the notch and dynamic island properly." },
          { lead: "Radar decluttered", text: "Search and per-slot adding moved to Explore. The home screen is now the domain switcher, your pulses, your queues as poster rails, and slot creation." },
          { lead: "New app icon", text: "A heart inside a radar sweep, across every icon size and the iOS home screen." },
        ],
      },
      {
        heading: "Fixed",
        items: [
          { lead: "Restaurant recommendations landing in your watch list", text: "A restaurant a friend sent you went into Recommended to me for films. Recommendations now go to the right domain, and anything previously misfiled was moved." },
        ],
      },
    ],
  },
  {
    seq: 6,
    version: "0.6",
    date: "2026-07-24",
    title: "Eat — restaurants join the radar",
    summary: "Radar stops being only about screens. Keep slots of places to eat, with hours, prices and directions.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Eat domain", text: "A Watch/Eat switch on the Radar home. The same slots, search, and title pages now work for restaurants too, and your choice is remembered." },
          { lead: "Restaurant search", text: "Search by name or cuisine, or tap Nearby to see what's popular around you." },
          { lead: "Restaurant pages", text: "An open-now badge, address, hours you can expand, cuisine, price level and rating, plus links to Maps, phone, and their website." },
          { lead: "Eat starter slots", text: "Want to try, Go-to spots (which keeps its entries instead of clearing), and Recommended to me." },
          { lead: "Location", text: "Radar can use your location to sort by what's near. If you say no, everything still works, just without distances." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "Statuses speak the right language per domain", text: "Restaurants use Want to try, Been there, and Not for me, with a Would go again toggle that feeds your Go-to spots." },
        ],
      },
    ],
  },
  {
    seq: 5,
    version: "0.5",
    date: "2026-07-24",
    title: "Friends",
    summary: "Add friends with a code, see what they're watching, and send them something directly — plus a nav that puts Radar at the centre.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Friend codes", text: "Everyone gets a short code. Type someone's in and you're friends instantly, both ways." },
          { lead: "Find friends by name", text: "Search for people and send a request they can accept." },
          { lead: "Friends tab", text: "Your people, in the bottom nav." },
          { lead: "Friend profiles", text: "Their radar, what they've finished and rated, and the parties you've been in together." },
          { lead: "Recommend to a friend", text: "Send a title from its page. It lands in their Recommended to me slot with your name attached, so they know who sent it." },
          { lead: "Five statuses", text: "Want to, Watching, Done, Stopped, and Not for me, on every title page." },
          { lead: "Would watch again", text: "A toggle that appears when you mark something Done and drops it into your Rewatch slot." },
          { lead: "History on the You page", text: "Everything you've finished, with ratings you can edit in place." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "Library tab is gone", text: "Radar is home. Global search, quick want-to adds, and the stale and morning-after cards moved onto it." },
          { lead: "Statuses drive your slots", text: "Marking something Watching or Done moves it between the right slots automatically, instead of you managing both." },
        ],
      },
      {
        heading: "Fixed",
        items: [
          { lead: "Friends' titles leaking into your screens", text: "After friends launched, a friend's Recommended slot could appear on your radar and their watches could show up in your history. Every screen now shows only your own rows." },
          { lead: "Stopped and Not for me not sticking", text: "Those statuses were dropped when the library reloaded. They stay put now." },
          { lead: "Sluggish taps", text: "Status, rating, and note taps update instantly instead of re-downloading your whole library first, which got slow after a big import." },
        ],
      },
    ],
  },
  {
    seq: 4,
    version: "0.4",
    date: "2026-07-24",
    title: "Slots and the Radar home",
    summary: "Your lists become slots — small, living queues like \"high movies\" or \"date night\" — and the Radar screen becomes home.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Slots", text: "Curated queues that stay current instead of a single list that grows forever. Think \"high movies\", \"date night\", \"rewatch\"." },
          { lead: "Radar home", text: "A new home screen showing every slot at a glance. It's now the first tab and where the app opens." },
          { lead: "Starter slots", text: "Everyone gets Watching now, Up next, Rewatch, and Recommended to me, ready to use." },
          { lead: "Slots that behave like playlists", text: "Each slot decides what happens when you finish something in it: drop it, send it to the back of the queue, or leave it alone. Rewatch loops; the rest clear out." },
          { lead: "Custom slots", text: "Make your own, name it, give it an emoji, choose whether it loops." },
          { lead: "Reordering", text: "Move titles up and down inside a slot to set what's next." },
          { lead: "Search inside a slot", text: "Add straight into the slot you're looking at." },
        ],
      },
    ],
  },
  {
    seq: 3,
    version: "0.3",
    date: "2026-07-24",
    title: "Better cards, filters and taste controls",
    summary: "Notes and \"who recommended it\" on your titles, filters for a library that got big, and direct control over your taste.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Notes on your cards", text: "Jot down why a title is on your list, right on its page." },
          { lead: "Recommended by", text: "A card can remember who told you about it." },
          { lead: "Library filters", text: "Filter by runtime and genre with chips built from what you actually have, so you never see an empty filter." },
          { lead: "Stale nudge", text: "A show you started but haven't touched in 60 days gets a gentle prompt: keep it, or take it off the radar." },
          { lead: "Taste chips", text: "On the You page, set any genre to neutral, love, or avoid. These go straight into party picks, so you can steer the AI by hand instead of waiting for it to learn." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "Clearer lobby copy", text: "The party lobby now says out loud that people don't have to swipe at the same time." },
        ],
      },
    ],
  },
  {
    seq: 2,
    version: "0.2",
    date: "2026-07-24",
    title: "Netflix history import",
    summary: "Upload the viewing history Netflix gives you and Radar fills in years of watches in one go.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Netflix history import", text: "On the You page, upload the CSV Netflix exports from your account page. Radar matches each title, groups episodes back into the show they belong to, and marks them finished." },
          { lead: "Import preview", text: "You see what was found and how many titles will be imported before anything is written, capped at the 400 most recent." },
          { lead: "Live progress", text: "A progress bar during the import and a summary of anything that couldn't be matched at the end." },
        ],
      },
      {
        heading: "Changed",
        items: [
          { lead: "Imports never overwrite you", text: "Ratings and want-to entries you already had survive a re-import untouched." },
          { lead: "Imported titles count as seen", text: "Party picks stop suggesting films you watched years ago, and your taste profile updates from the new history." },
        ],
      },
    ],
  },
  {
    seq: 1,
    version: "0.1",
    date: "2026-07-24",
    title: "Movie night, decided",
    summary: "The first version of Radar — build a library, throw a party, and let everyone swipe and vote their way to one film.",
    sections: [
      {
        heading: "Added",
        items: [
          { lead: "Accounts", text: "Sign up and sign in with an email address and a password. Your session sticks around, so you only do it once per device." },
          { lead: "Onboarding", text: "A quick three-step start: pick a display name, calibrate your taste, and tell us which streaming services you pay for." },
          { lead: "Taste calibration", text: "Rate up to 24 well-known titles as Loved, Meh, Haven't seen, or Never would. Skippable after 12. Everything you tap teaches the app what to suggest." },
          { lead: "Your library", text: "Search films and shows, add them to your want-to list, mark them finished, and rate them out of 10." },
          { lead: "Title pages", text: "Poster and backdrop art, the blurb, genres, runtime, and where you can stream it, with your own services highlighted." },
          { lead: "Parties", text: "Start a party, get a six-character code, and share a join link. Everyone who joins shows up in a live lobby." },
          { lead: "Party constraints", text: "The host sets what kind of night it is: film or show, how long you've got, and whether it has to be streamable by everyone." },
          { lead: "Mood check-in", text: "Before picks are generated, everyone says how much energy they have and picks up to three vibes." },
          { lead: "AI picks", text: "The host taps generate and Radar builds a shortlist from everyone's want-to lists plus fresh suggestions, filters out anything that breaks the rules or that someone has already seen, scores what's left against the group's taste, mood, quality and freshness, then has Gemini reorder the finalists and write a one-line reason for each." },
          { lead: "Swipe deck", text: "Swipe right for yes, left for no. Everyone can swipe at their own pace, and each person gets one anonymous veto to kill a title outright." },
          { lead: "Voting", text: "Survivors go to a vote where everyone spreads three points across the finalists, with running totals." },
          { lead: "The reveal", text: "Confetti, the winner, and a \"watch on\" link that prefers a service you actually subscribe to." },
          { lead: "Morning-after pulse", text: "Twelve hours later, Radar asks whether you actually watched it, so your history stays honest." },
          { lead: "Install it like an app", text: "Radar installs to your home screen, works offline for what it has already loaded, and shows a tap-to-update pill when a new version is out." },
        ],
      },
    ],
  },
];

/** Highest sequence in this build — compared against profiles.last_seen_release_seq. */
export const LATEST_RELEASE_SEQ = 11;
